/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ResidentRouteImport } from './routes/resident'
import { Route as SecurityRouteImport } from './routes/security'
import { Route as SuperAdminRouteImport } from './routes/super-admin'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminComplaintsRouteImport } from './routes/admin.complaints'
import { Route as AdminEventsRouteImport } from './routes/admin.events'
import { Route as AdminFacilitiesRouteImport } from './routes/admin.facilities'
import { Route as AdminMaintenanceRouteImport } from './routes/admin.maintenance'
import { Route as AdminNoticesRouteImport } from './routes/admin.notices'
import { Route as AdminParkingRouteImport } from './routes/admin.parking'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminResidentsRouteImport } from './routes/admin.residents'
import { Route as AdminStaffRouteImport } from './routes/admin.staff'
import { Route as AdminVisitorsRouteImport } from './routes/admin.visitors'
import { Route as ResidentIndexRouteImport } from './routes/resident.index'
import { Route as ResidentComplaintsRouteImport } from './routes/resident.complaints'
import { Route as ResidentEventsRouteImport } from './routes/resident.events'
import { Route as ResidentFacilitiesRouteImport } from './routes/resident.facilities'
import { Route as ResidentMaintenanceRouteImport } from './routes/resident.maintenance'
import { Route as ResidentNoticesRouteImport } from './routes/resident.notices'
import { Route as ResidentProfileRouteImport } from './routes/resident.profile'
import { Route as ResidentVisitorsRouteImport } from './routes/resident.visitors'
import { Route as SecurityIndexRouteImport } from './routes/security.index'
import { Route as SecurityEntryRouteImport } from './routes/security.entry'
import { Route as SecurityExitRouteImport } from './routes/security.exit'
import { Route as SecurityHistoryRouteImport } from './routes/security.history'
import { Route as SuperAdminIndexRouteImport } from './routes/super-admin.index'
import { Route as SuperAdminRolesRouteImport } from './routes/super-admin.roles'
import { Route as SuperAdminSettingsRouteImport } from './routes/super-admin.settings'
import { Route as SuperAdminUsersRouteImport } from './routes/super-admin.users'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ResidentRoute = ResidentRouteImport.update({
  id: '/resident',
  path: '/resident',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityRoute = SecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperAdminRoute = SuperAdminRouteImport.update({
  id: '/super-admin',
  path: '/super-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminComplaintsRoute = AdminComplaintsRouteImport.update({
  id: '/complaints',
  path: '/complaints',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEventsRoute = AdminEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFacilitiesRoute = AdminFacilitiesRouteImport.update({
  id: '/facilities',
  path: '/facilities',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMaintenanceRoute = AdminMaintenanceRouteImport.update({
  id: '/maintenance',
  path: '/maintenance',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNoticesRoute = AdminNoticesRouteImport.update({
  id: '/notices',
  path: '/notices',
  getParentRoute: () => AdminRoute,
} as any)
const AdminParkingRoute = AdminParkingRouteImport.update({
  id: '/parking',
  path: '/parking',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminResidentsRoute = AdminResidentsRouteImport.update({
  id: '/residents',
  path: '/residents',
  getParentRoute: () => AdminRoute,
} as any)
const AdminStaffRoute = AdminStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => AdminRoute,
} as any)
const AdminVisitorsRoute = AdminVisitorsRouteImport.update({
  id: '/visitors',
  path: '/visitors',
  getParentRoute: () => AdminRoute,
} as any)
const ResidentIndexRoute = ResidentIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ResidentRoute,
} as any)
const ResidentComplaintsRoute = ResidentComplaintsRouteImport.update({
  id: '/complaints',
  path: '/complaints',
  getParentRoute: () => ResidentRoute,
} as any)
const ResidentEventsRoute = ResidentEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => ResidentRoute,
} as any)
const ResidentFacilitiesRoute = ResidentFacilitiesRouteImport.update({
  id: '/facilities',
  path: '/facilities',
  getParentRoute: () => ResidentRoute,
} as any)
const ResidentMaintenanceRoute = ResidentMaintenanceRouteImport.update({
  id: '/maintenance',
  path: '/maintenance',
  getParentRoute: () => ResidentRoute,
} as any)
const ResidentNoticesRoute = ResidentNoticesRouteImport.update({
  id: '/notices',
  path: '/notices',
  getParentRoute: () => ResidentRoute,
} as any)
const ResidentProfileRoute = ResidentProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => ResidentRoute,
} as any)
const ResidentVisitorsRoute = ResidentVisitorsRouteImport.update({
  id: '/visitors',
  path: '/visitors',
  getParentRoute: () => ResidentRoute,
} as any)
const SecurityIndexRoute = SecurityIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SecurityRoute,
} as any)
const SecurityEntryRoute = SecurityEntryRouteImport.update({
  id: '/entry',
  path: '/entry',
  getParentRoute: () => SecurityRoute,
} as any)
const SecurityExitRoute = SecurityExitRouteImport.update({
  id: '/exit',
  path: '/exit',
  getParentRoute: () => SecurityRoute,
} as any)
const SecurityHistoryRoute = SecurityHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => SecurityRoute,
} as any)
const SuperAdminIndexRoute = SuperAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SuperAdminRoute,
} as any)
const SuperAdminRolesRoute = SuperAdminRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => SuperAdminRoute,
} as any)
const SuperAdminSettingsRoute = SuperAdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => SuperAdminRoute,
} as any)
const SuperAdminUsersRoute = SuperAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => SuperAdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/resident': typeof ResidentRouteWithChildren
  '/security': typeof SecurityRouteWithChildren
  '/super-admin': typeof SuperAdminRouteWithChildren
  '/admin/complaints': typeof AdminComplaintsRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/facilities': typeof AdminFacilitiesRoute
  '/admin/maintenance': typeof AdminMaintenanceRoute
  '/admin/notices': typeof AdminNoticesRoute
  '/admin/parking': typeof AdminParkingRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/residents': typeof AdminResidentsRoute
  '/admin/staff': typeof AdminStaffRoute
  '/admin/visitors': typeof AdminVisitorsRoute
  '/resident/complaints': typeof ResidentComplaintsRoute
  '/resident/events': typeof ResidentEventsRoute
  '/resident/facilities': typeof ResidentFacilitiesRoute
  '/resident/maintenance': typeof ResidentMaintenanceRoute
  '/resident/notices': typeof ResidentNoticesRoute
  '/resident/profile': typeof ResidentProfileRoute
  '/resident/visitors': typeof ResidentVisitorsRoute
  '/security/entry': typeof SecurityEntryRoute
  '/security/exit': typeof SecurityExitRoute
  '/security/history': typeof SecurityHistoryRoute
  '/super-admin/roles': typeof SuperAdminRolesRoute
  '/super-admin/settings': typeof SuperAdminSettingsRoute
  '/super-admin/users': typeof SuperAdminUsersRoute
  '/admin/': typeof AdminIndexRoute
  '/resident/': typeof ResidentIndexRoute
  '/security/': typeof SecurityIndexRoute
  '/super-admin/': typeof SuperAdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin/complaints': typeof AdminComplaintsRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/facilities': typeof AdminFacilitiesRoute
  '/admin/maintenance': typeof AdminMaintenanceRoute
  '/admin/notices': typeof AdminNoticesRoute
  '/admin/parking': typeof AdminParkingRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/residents': typeof AdminResidentsRoute
  '/admin/staff': typeof AdminStaffRoute
  '/admin/visitors': typeof AdminVisitorsRoute
  '/resident/complaints': typeof ResidentComplaintsRoute
  '/resident/events': typeof ResidentEventsRoute
  '/resident/facilities': typeof ResidentFacilitiesRoute
  '/resident/maintenance': typeof ResidentMaintenanceRoute
  '/resident/notices': typeof ResidentNoticesRoute
  '/resident/profile': typeof ResidentProfileRoute
  '/resident/visitors': typeof ResidentVisitorsRoute
  '/security/entry': typeof SecurityEntryRoute
  '/security/exit': typeof SecurityExitRoute
  '/security/history': typeof SecurityHistoryRoute
  '/super-admin/roles': typeof SuperAdminRolesRoute
  '/super-admin/settings': typeof SuperAdminSettingsRoute
  '/super-admin/users': typeof SuperAdminUsersRoute
  '/admin': typeof AdminIndexRoute
  '/resident': typeof ResidentIndexRoute
  '/security': typeof SecurityIndexRoute
  '/super-admin': typeof SuperAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/resident': typeof ResidentRouteWithChildren
  '/security': typeof SecurityRouteWithChildren
  '/super-admin': typeof SuperAdminRouteWithChildren
  '/admin/complaints': typeof AdminComplaintsRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/facilities': typeof AdminFacilitiesRoute
  '/admin/maintenance': typeof AdminMaintenanceRoute
  '/admin/notices': typeof AdminNoticesRoute
  '/admin/parking': typeof AdminParkingRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/residents': typeof AdminResidentsRoute
  '/admin/staff': typeof AdminStaffRoute
  '/admin/visitors': typeof AdminVisitorsRoute
  '/resident/complaints': typeof ResidentComplaintsRoute
  '/resident/events': typeof ResidentEventsRoute
  '/resident/facilities': typeof ResidentFacilitiesRoute
  '/resident/maintenance': typeof ResidentMaintenanceRoute
  '/resident/notices': typeof ResidentNoticesRoute
  '/resident/profile': typeof ResidentProfileRoute
  '/resident/visitors': typeof ResidentVisitorsRoute
  '/security/entry': typeof SecurityEntryRoute
  '/security/exit': typeof SecurityExitRoute
  '/security/history': typeof SecurityHistoryRoute
  '/super-admin/roles': typeof SuperAdminRolesRoute
  '/super-admin/settings': typeof SuperAdminSettingsRoute
  '/super-admin/users': typeof SuperAdminUsersRoute
  '/admin/': typeof AdminIndexRoute
  '/resident/': typeof ResidentIndexRoute
  '/security/': typeof SecurityIndexRoute
  '/super-admin/': typeof SuperAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/forgot-password'
    | '/reset-password'
    | '/resident'
    | '/security'
    | '/super-admin'
    | '/admin/complaints'
    | '/admin/events'
    | '/admin/facilities'
    | '/admin/maintenance'
    | '/admin/notices'
    | '/admin/parking'
    | '/admin/reports'
    | '/admin/residents'
    | '/admin/staff'
    | '/admin/visitors'
    | '/resident/complaints'
    | '/resident/events'
    | '/resident/facilities'
    | '/resident/maintenance'
    | '/resident/notices'
    | '/resident/profile'
    | '/resident/visitors'
    | '/security/entry'
    | '/security/exit'
    | '/security/history'
    | '/super-admin/roles'
    | '/super-admin/settings'
    | '/super-admin/users'
    | '/admin/'
    | '/resident/'
    | '/security/'
    | '/super-admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/forgot-password'
    | '/reset-password'
    | '/admin/complaints'
    | '/admin/events'
    | '/admin/facilities'
    | '/admin/maintenance'
    | '/admin/notices'
    | '/admin/parking'
    | '/admin/reports'
    | '/admin/residents'
    | '/admin/staff'
    | '/admin/visitors'
    | '/resident/complaints'
    | '/resident/events'
    | '/resident/facilities'
    | '/resident/maintenance'
    | '/resident/notices'
    | '/resident/profile'
    | '/resident/visitors'
    | '/security/entry'
    | '/security/exit'
    | '/security/history'
    | '/super-admin/roles'
    | '/super-admin/settings'
    | '/super-admin/users'
    | '/admin'
    | '/resident'
    | '/security'
    | '/super-admin'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/forgot-password'
    | '/reset-password'
    | '/resident'
    | '/security'
    | '/super-admin'
    | '/admin/complaints'
    | '/admin/events'
    | '/admin/facilities'
    | '/admin/maintenance'
    | '/admin/notices'
    | '/admin/parking'
    | '/admin/reports'
    | '/admin/residents'
    | '/admin/staff'
    | '/admin/visitors'
    | '/resident/complaints'
    | '/resident/events'
    | '/resident/facilities'
    | '/resident/maintenance'
    | '/resident/notices'
    | '/resident/profile'
    | '/resident/visitors'
    | '/security/entry'
    | '/security/exit'
    | '/security/history'
    | '/super-admin/roles'
    | '/super-admin/settings'
    | '/super-admin/users'
    | '/admin/'
    | '/resident/'
    | '/security/'
    | '/super-admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ResidentRoute: typeof ResidentRouteWithChildren
  SecurityRoute: typeof SecurityRouteWithChildren
  SuperAdminRoute: typeof SuperAdminRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resident': {
      id: '/resident'
      path: '/resident'
      fullPath: '/resident'
      preLoaderRoute: typeof ResidentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security': {
      id: '/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof SecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/super-admin': {
      id: '/super-admin'
      path: '/super-admin'
      fullPath: '/super-admin'
      preLoaderRoute: typeof SuperAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/complaints': {
      id: '/admin/complaints'
      path: '/complaints'
      fullPath: '/admin/complaints'
      preLoaderRoute: typeof AdminComplaintsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/events': {
      id: '/admin/events'
      path: '/events'
      fullPath: '/admin/events'
      preLoaderRoute: typeof AdminEventsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/facilities': {
      id: '/admin/facilities'
      path: '/facilities'
      fullPath: '/admin/facilities'
      preLoaderRoute: typeof AdminFacilitiesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/maintenance': {
      id: '/admin/maintenance'
      path: '/maintenance'
      fullPath: '/admin/maintenance'
      preLoaderRoute: typeof AdminMaintenanceRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/notices': {
      id: '/admin/notices'
      path: '/notices'
      fullPath: '/admin/notices'
      preLoaderRoute: typeof AdminNoticesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/parking': {
      id: '/admin/parking'
      path: '/parking'
      fullPath: '/admin/parking'
      preLoaderRoute: typeof AdminParkingRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/residents': {
      id: '/admin/residents'
      path: '/residents'
      fullPath: '/admin/residents'
      preLoaderRoute: typeof AdminResidentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/staff': {
      id: '/admin/staff'
      path: '/staff'
      fullPath: '/admin/staff'
      preLoaderRoute: typeof AdminStaffRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/visitors': {
      id: '/admin/visitors'
      path: '/visitors'
      fullPath: '/admin/visitors'
      preLoaderRoute: typeof AdminVisitorsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/resident/': {
      id: '/resident/'
      path: '/'
      fullPath: '/resident/'
      preLoaderRoute: typeof ResidentIndexRouteImport
      parentRoute: typeof ResidentRoute
    }
    '/resident/complaints': {
      id: '/resident/complaints'
      path: '/complaints'
      fullPath: '/resident/complaints'
      preLoaderRoute: typeof ResidentComplaintsRouteImport
      parentRoute: typeof ResidentRoute
    }
    '/resident/events': {
      id: '/resident/events'
      path: '/events'
      fullPath: '/resident/events'
      preLoaderRoute: typeof ResidentEventsRouteImport
      parentRoute: typeof ResidentRoute
    }
    '/resident/facilities': {
      id: '/resident/facilities'
      path: '/facilities'
      fullPath: '/resident/facilities'
      preLoaderRoute: typeof ResidentFacilitiesRouteImport
      parentRoute: typeof ResidentRoute
    }
    '/resident/maintenance': {
      id: '/resident/maintenance'
      path: '/maintenance'
      fullPath: '/resident/maintenance'
      preLoaderRoute: typeof ResidentMaintenanceRouteImport
      parentRoute: typeof ResidentRoute
    }
    '/resident/notices': {
      id: '/resident/notices'
      path: '/notices'
      fullPath: '/resident/notices'
      preLoaderRoute: typeof ResidentNoticesRouteImport
      parentRoute: typeof ResidentRoute
    }
    '/resident/profile': {
      id: '/resident/profile'
      path: '/profile'
      fullPath: '/resident/profile'
      preLoaderRoute: typeof ResidentProfileRouteImport
      parentRoute: typeof ResidentRoute
    }
    '/resident/visitors': {
      id: '/resident/visitors'
      path: '/visitors'
      fullPath: '/resident/visitors'
      preLoaderRoute: typeof ResidentVisitorsRouteImport
      parentRoute: typeof ResidentRoute
    }
    '/security/': {
      id: '/security/'
      path: '/'
      fullPath: '/security/'
      preLoaderRoute: typeof SecurityIndexRouteImport
      parentRoute: typeof SecurityRoute
    }
    '/security/entry': {
      id: '/security/entry'
      path: '/entry'
      fullPath: '/security/entry'
      preLoaderRoute: typeof SecurityEntryRouteImport
      parentRoute: typeof SecurityRoute
    }
    '/security/exit': {
      id: '/security/exit'
      path: '/exit'
      fullPath: '/security/exit'
      preLoaderRoute: typeof SecurityExitRouteImport
      parentRoute: typeof SecurityRoute
    }
    '/security/history': {
      id: '/security/history'
      path: '/history'
      fullPath: '/security/history'
      preLoaderRoute: typeof SecurityHistoryRouteImport
      parentRoute: typeof SecurityRoute
    }
    '/super-admin/': {
      id: '/super-admin/'
      path: '/'
      fullPath: '/super-admin/'
      preLoaderRoute: typeof SuperAdminIndexRouteImport
      parentRoute: typeof SuperAdminRoute
    }
    '/super-admin/roles': {
      id: '/super-admin/roles'
      path: '/roles'
      fullPath: '/super-admin/roles'
      preLoaderRoute: typeof SuperAdminRolesRouteImport
      parentRoute: typeof SuperAdminRoute
    }
    '/super-admin/settings': {
      id: '/super-admin/settings'
      path: '/settings'
      fullPath: '/super-admin/settings'
      preLoaderRoute: typeof SuperAdminSettingsRouteImport
      parentRoute: typeof SuperAdminRoute
    }
    '/super-admin/users': {
      id: '/super-admin/users'
      path: '/users'
      fullPath: '/super-admin/users'
      preLoaderRoute: typeof SuperAdminUsersRouteImport
      parentRoute: typeof SuperAdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminComplaintsRoute: typeof AdminComplaintsRoute
  AdminEventsRoute: typeof AdminEventsRoute
  AdminFacilitiesRoute: typeof AdminFacilitiesRoute
  AdminMaintenanceRoute: typeof AdminMaintenanceRoute
  AdminNoticesRoute: typeof AdminNoticesRoute
  AdminParkingRoute: typeof AdminParkingRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminResidentsRoute: typeof AdminResidentsRoute
  AdminStaffRoute: typeof AdminStaffRoute
  AdminVisitorsRoute: typeof AdminVisitorsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminComplaintsRoute: AdminComplaintsRoute,
  AdminEventsRoute: AdminEventsRoute,
  AdminFacilitiesRoute: AdminFacilitiesRoute,
  AdminMaintenanceRoute: AdminMaintenanceRoute,
  AdminNoticesRoute: AdminNoticesRoute,
  AdminParkingRoute: AdminParkingRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminResidentsRoute: AdminResidentsRoute,
  AdminStaffRoute: AdminStaffRoute,
  AdminVisitorsRoute: AdminVisitorsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface ResidentRouteChildren {
  ResidentComplaintsRoute: typeof ResidentComplaintsRoute
  ResidentEventsRoute: typeof ResidentEventsRoute
  ResidentFacilitiesRoute: typeof ResidentFacilitiesRoute
  ResidentMaintenanceRoute: typeof ResidentMaintenanceRoute
  ResidentNoticesRoute: typeof ResidentNoticesRoute
  ResidentProfileRoute: typeof ResidentProfileRoute
  ResidentVisitorsRoute: typeof ResidentVisitorsRoute
  ResidentIndexRoute: typeof ResidentIndexRoute
}

const ResidentRouteChildren: ResidentRouteChildren = {
  ResidentComplaintsRoute: ResidentComplaintsRoute,
  ResidentEventsRoute: ResidentEventsRoute,
  ResidentFacilitiesRoute: ResidentFacilitiesRoute,
  ResidentMaintenanceRoute: ResidentMaintenanceRoute,
  ResidentNoticesRoute: ResidentNoticesRoute,
  ResidentProfileRoute: ResidentProfileRoute,
  ResidentVisitorsRoute: ResidentVisitorsRoute,
  ResidentIndexRoute: ResidentIndexRoute,
}

const ResidentRouteWithChildren = ResidentRoute._addFileChildren(
  ResidentRouteChildren,
)

interface SecurityRouteChildren {
  SecurityEntryRoute: typeof SecurityEntryRoute
  SecurityExitRoute: typeof SecurityExitRoute
  SecurityHistoryRoute: typeof SecurityHistoryRoute
  SecurityIndexRoute: typeof SecurityIndexRoute
}

const SecurityRouteChildren: SecurityRouteChildren = {
  SecurityEntryRoute: SecurityEntryRoute,
  SecurityExitRoute: SecurityExitRoute,
  SecurityHistoryRoute: SecurityHistoryRoute,
  SecurityIndexRoute: SecurityIndexRoute,
}

const SecurityRouteWithChildren = SecurityRoute._addFileChildren(
  SecurityRouteChildren,
)

interface SuperAdminRouteChildren {
  SuperAdminRolesRoute: typeof SuperAdminRolesRoute
  SuperAdminSettingsRoute: typeof SuperAdminSettingsRoute
  SuperAdminUsersRoute: typeof SuperAdminUsersRoute
  SuperAdminIndexRoute: typeof SuperAdminIndexRoute
}

const SuperAdminRouteChildren: SuperAdminRouteChildren = {
  SuperAdminRolesRoute: SuperAdminRolesRoute,
  SuperAdminSettingsRoute: SuperAdminSettingsRoute,
  SuperAdminUsersRoute: SuperAdminUsersRoute,
  SuperAdminIndexRoute: SuperAdminIndexRoute,
}

const SuperAdminRouteWithChildren = SuperAdminRoute._addFileChildren(
  SuperAdminRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ResidentRoute: ResidentRouteWithChildren,
  SecurityRoute: SecurityRouteWithChildren,
  SuperAdminRoute: SuperAdminRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
